"""Initial schema

Revision ID: 1ff1215ea4e2
Revises: 
Create Date: 2026-05-25 13:55:36.979857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff1215ea4e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stunting_status', sa.String(length=30), nullable=False),
    sa.Column('min_age_months', sa.Integer(), nullable=False),
    sa.Column('max_age_months', sa.Integer(), nullable=False),
    sa.Column('recommendation_text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardians',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('who_standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('age_in_months', sa.Integer(), nullable=False),
    sa.Column('measure_type', sa.String(length=10), nullable=False),
    sa.Column('l', sa.Float(), nullable=False),
    sa.Column('m', sa.Float(), nullable=False),
    sa.Column('s', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guardian_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('age_in_months', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('head_circumference', sa.Float(), nullable=True),
    sa.Column('measured_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stunting_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('measurement_id', sa.String(length=36), nullable=False),
    sa.Column('haz_zscore', sa.Float(), nullable=False),
    sa.Column('waz_zscore', sa.Float(), nullable=False),
    sa.Column('whz_zscore', sa.Float(), nullable=False),
    sa.Column('stunting_status_who', sa.String(length=30), nullable=False),
    sa.Column('wasting_status_who', sa.String(length=30), nullable=False),
    sa.Column('underweight_status_who', sa.String(length=30), nullable=False),
    sa.Column('stunting_status_ml', sa.String(length=30), nullable=True),
    sa.Column('wasting_status_ml', sa.String(length=30), nullable=True),
    sa.Column('ml_stunting_confidence', sa.Float(), nullable=True),
    sa.Column('ml_wasting_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stunting_results')
    op.drop_table('measurements')
    op.drop_table('children')
    op.drop_table('who_standards')
    op.drop_table('guardians')
    op.drop_table('food_recommendations')
    # ### end Alembic commands ###
