"""Add NIK and Education

Revision ID: 2ee587d27e45
Revises: 6b94b4aceead
Create Date: 2026-05-26 16:21:02.201265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee587d27e45'
down_revision: Union[str, Sequence[str], None] = '6b94b4aceead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('children', sa.Column('nik', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'children', ['nik'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'children', type_='unique')
    op.drop_column('children', 'nik')
    op.drop_table('educations')
    # ### end Alembic commands ###
