"""Add User and RBAC

Revision ID: 6b94b4aceead
Revises: 1ff1215ea4e2
Create Date: 2026-05-25 14:55:28.977643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b94b4aceead'
down_revision: Union[str, Sequence[str], None] = '1ff1215ea4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('guardians', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('guardians', sa.Column('nomor_kk', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'guardians', ['user_id'])
    op.create_foreign_key(None, 'guardians', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guardians', type_='foreignkey')
    op.drop_constraint(None, 'guardians', type_='unique')
    op.drop_column('guardians', 'nomor_kk')
    op.drop_column('guardians', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
