"""remove_who_standards

Revision ID: a2d974968b18
Revises: 2ee587d27e45
Create Date: 2026-07-27 07:23:51.635805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2d974968b18'
down_revision: Union[str, Sequence[str], None] = '2ee587d27e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('who_standards')
    op.drop_column('stunting_results', 'underweight_status_who')
    op.drop_column('stunting_results', 'whz_zscore')
    op.drop_column('stunting_results', 'haz_zscore')
    op.drop_column('stunting_results', 'wasting_status_who')
    op.drop_column('stunting_results', 'stunting_status_who')
    op.drop_column('stunting_results', 'waz_zscore')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stunting_results', sa.Column('waz_zscore', mysql.FLOAT(), nullable=False))
    op.add_column('stunting_results', sa.Column('stunting_status_who', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('stunting_results', sa.Column('wasting_status_who', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('stunting_results', sa.Column('haz_zscore', mysql.FLOAT(), nullable=False))
    op.add_column('stunting_results', sa.Column('whz_zscore', mysql.FLOAT(), nullable=False))
    op.add_column('stunting_results', sa.Column('underweight_status_who', mysql.VARCHAR(length=30), nullable=False))
    op.create_table('who_standards',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('age_in_months', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('measure_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('l', mysql.FLOAT(), nullable=False),
    sa.Column('m', mysql.FLOAT(), nullable=False),
    sa.Column('s', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
